/** Re-exporta tipos canônicos do domínio Agro. */
export type {
  LeadStatus,
  LeadPriority,
  OpportunityStage,
  MatterStatus,
  MatterUrgency,
  RiskLevel,
  TaskPriority,
  TaskStatus,
  AccountType,
  RelationshipStatus,
  OpportunityPriority,
  AgroRole,
  Lead,
  Account,
  Opportunity,
  Matter,
  Task,
  AgroUser,
  CrmStats,
} from "@shared/agro/types";