import type {
  Account,
  Lead,
  Matter,
  Opportunity,
  Task,
} from "./crm-types";

/** Dados 100% fictícios — nunca substituir por clientes reais sem backend */

export const MOCK_LEADS: Lead[] = [
  {
    id: "LD-001",
    name: "Fazenda Horizonte Ltda.",
    contact: "contato@fazhorizonte-demo.br",
    region: "MT — Sorriso",
    crop: "Soja / milho",
    source: "Indicação parceiro",
    status: "qualificado",
    owner: "Ana Ribeiro",
    createdAt: "2026-05-28",
    notes: "Interesse em regularização de glebas e revisão de arrendamentos.",
  },
  {
    id: "LD-002",
    name: "Cooperativa Vale Verde (mock)",
    contact: "juridico@valeverde-demo.coop",
    region: "PR — Cascavel",
    crop: "Café / grãos",
    source: "Evento setorial",
    status: "qualificando",
    owner: "Carlos Mendes",
    createdAt: "2026-06-02",
    notes: "Demanda em governança associativa e contratos de venda.",
  },
  {
    id: "LD-003",
    name: "Sítio Boa Esperança",
    contact: "familia.boaesperanca@demo.mail",
    region: "GO — Rio Verde",
    crop: "Soja",
    source: "Site institucional",
    status: "novo",
    owner: "Ana Ribeiro",
    createdAt: "2026-06-07",
    notes: "Primeiro contato — sucessão familiar e holding rural.",
  },
  {
    id: "LD-004",
    name: "Agro Norte Trading S.A. (fictícia)",
    contact: "comercial@agronortetrade-demo.br",
    region: "SP — São Paulo",
    crop: "Commodities",
    source: "Outbound",
    status: "qualificado",
    owner: "Carlos Mendes",
    createdAt: "2026-05-15",
    notes: "Contratos de compra e venda com cláusulas de hedge.",
  },
  {
    id: "LD-005",
    name: "Grupo Campos do Sul",
    contact: "diretoria@camposulsul-demo.br",
    region: "RS — Passo Fundo",
    crop: "Trigo / pecuária",
    source: "Referência interna",
    status: "descartado",
    owner: "Ana Ribeiro",
    createdAt: "2026-04-20",
    notes: "Sem fit de escopo neste momento.",
  },
];

export const MOCK_ACCOUNTS: Account[] = [
  {
    id: "AC-101",
    name: "Fazenda Horizonte Ltda.",
    type: "produtor",
    region: "MT — Sorriso",
    areaHa: 4200,
    mainCrop: "Soja",
    owner: "Ana Ribeiro",
    activeMatters: 2,
    activeOpportunities: 1,
    since: "2024-03",
  },
  {
    id: "AC-102",
    name: "Cooperativa Vale Verde",
    type: "cooperativa",
    region: "PR — Cascavel",
    areaHa: 0,
    mainCrop: "Multi",
    owner: "Carlos Mendes",
    activeMatters: 1,
    activeOpportunities: 1,
    since: "2023-11",
  },
  {
    id: "AC-103",
    name: "Família Oliveira Agro",
    type: "familia",
    region: "GO — Rio Verde",
    areaHa: 1850,
    mainCrop: "Soja / algodão",
    owner: "Ana Ribeiro",
    activeMatters: 3,
    activeOpportunities: 0,
    since: "2022-08",
  },
  {
    id: "AC-104",
    name: "CerealTech Indústria (mock)",
    type: "agroindustria",
    region: "MS — Dourados",
    areaHa: 0,
    mainCrop: "Processamento",
    owner: "Carlos Mendes",
    activeMatters: 2,
    activeOpportunities: 1,
    since: "2025-01",
  },
  {
    id: "AC-105",
    name: "Fundo Invest Agro I (fictício)",
    type: "investidor",
    region: "SP — São Paulo",
    areaHa: 0,
    mainCrop: "Portfolio",
    owner: "Ana Ribeiro",
    activeMatters: 1,
    activeOpportunities: 2,
    since: "2025-06",
  },
];

export const MOCK_OPPORTUNITIES: Opportunity[] = [
  {
    id: "OP-201",
    title: "Pacote regularização + contratos",
    accountName: "Fazenda Horizonte Ltda.",
    stage: "proposta",
    valueBrl: 185000,
    owner: "Ana Ribeiro",
    expectedClose: "2026-07-15",
    practice: "Imóveis rurais",
  },
  {
    id: "OP-202",
    title: "Governança e contratos associativos",
    accountName: "Cooperativa Vale Verde",
    stage: "qualificacao",
    valueBrl: 92000,
    owner: "Carlos Mendes",
    expectedClose: "2026-08-01",
    practice: "Societário",
  },
  {
    id: "OP-203",
    title: "Due diligence aquisição área",
    accountName: "Fundo Invest Agro I (fictício)",
    stage: "negociacao",
    valueBrl: 240000,
    owner: "Ana Ribeiro",
    expectedClose: "2026-06-30",
    practice: "M&A rural",
  },
  {
    id: "OP-204",
    title: "Renegociação crédito rural",
    accountName: "Família Oliveira Agro",
    stage: "contrato",
    valueBrl: 68000,
    owner: "Ana Ribeiro",
    expectedClose: "2026-06-12",
    practice: "Crédito rural",
  },
  {
    id: "OP-205",
    title: "Compliance ambiental planta",
    accountName: "CerealTech Indústria (mock)",
    stage: "proposta",
    valueBrl: 110000,
    owner: "Carlos Mendes",
    expectedClose: "2026-07-22",
    practice: "Ambiental",
  },
];

export const MOCK_MATTERS: Matter[] = [
  {
    id: "MT-301",
    title: "CAR e georreferenciamento — gleba norte",
    accountName: "Fazenda Horizonte Ltda.",
    practice: "Regularização",
    status: "em_andamento",
    risk: "medio",
    deadline: "2026-06-18",
    owner: "Ana Ribeiro",
    description: "Retificação de área e atualização documental.",
  },
  {
    id: "MT-302",
    title: "Contestação ambiental — área preservada",
    accountName: "Família Oliveira Agro",
    practice: "Contencioso",
    status: "aberta",
    risk: "alto",
    deadline: "2026-06-10",
    owner: "Carlos Mendes",
    description: "Prazo processual crítico — manifestação pendente.",
  },
  {
    id: "MT-303",
    title: "Revisão contratos de arrendamento",
    accountName: "Cooperativa Vale Verde",
    practice: "Contratos",
    status: "aguardando",
    risk: "baixo",
    deadline: "2026-06-25",
    owner: "Carlos Mendes",
    description: "Aguardando minuta da contraparte.",
  },
  {
    id: "MT-304",
    title: "Holding familiar e sucessão",
    accountName: "Família Oliveira Agro",
    practice: "Patrimonial",
    status: "em_andamento",
    risk: "medio",
    deadline: "2026-07-05",
    owner: "Ana Ribeiro",
    description: "Estruturação societária entre gerações.",
  },
  {
    id: "MT-305",
    title: "Licenciamento operacional unidade",
    accountName: "CerealTech Indústria (mock)",
    practice: "Ambiental",
    status: "em_andamento",
    risk: "critico",
    deadline: "2026-06-09",
    owner: "Carlos Mendes",
    description: "Condicionante com vencimento iminente.",
  },
];

export const MOCK_TASKS: Task[] = [
  {
    id: "TK-401",
    title: "Enviar proposta revisada — Horizonte",
    relatedTo: "OP-201",
    type: "comercial",
    priority: "alta",
    status: "pendente",
    dueDate: "2026-06-09",
    owner: "Ana Ribeiro",
  },
  {
    id: "TK-402",
    title: "Protocolar manifestação ambiental",
    relatedTo: "MT-302",
    type: "juridica",
    priority: "urgente",
    status: "atrasada",
    dueDate: "2026-06-08",
    owner: "Carlos Mendes",
  },
  {
    id: "TK-403",
    title: "Reunião diagnóstico — Sítio Boa Esperança",
    relatedTo: "LD-003",
    type: "comercial",
    priority: "media",
    status: "pendente",
    dueDate: "2026-06-11",
    owner: "Ana Ribeiro",
  },
  {
    id: "TK-404",
    title: "Coletar documentos CAR gleba norte",
    relatedTo: "MT-301",
    type: "operacional",
    priority: "alta",
    status: "em_andamento",
    dueDate: "2026-06-12",
    owner: "Ana Ribeiro",
  },
  {
    id: "TK-405",
    title: "Minuta contrato arrendamento — Vale Verde",
    relatedTo: "MT-303",
    type: "juridica",
    priority: "media",
    status: "pendente",
    dueDate: "2026-06-20",
    owner: "Carlos Mendes",
  },
  {
    id: "TK-406",
    title: "Follow-up due diligence — Fundo Invest",
    relatedTo: "OP-203",
    type: "comercial",
    priority: "alta",
    status: "em_andamento",
    dueDate: "2026-06-10",
    owner: "Ana Ribeiro",
  },
];

export const OPPORTUNITY_STAGES = [
  { id: "qualificacao" as const, label: "Qualificação" },
  { id: "proposta" as const, label: "Proposta" },
  { id: "negociacao" as const, label: "Negociação" },
  { id: "contrato" as const, label: "Contrato" },
  { id: "perdido" as const, label: "Perdido" },
];