/** Re-exporta tipos canônicos do domínio Agro. */
export type {
  LeadStatus,
  LeadPriority,
  OpportunityStage,
  MatterStatus,
  MatterUrgency,
  MatterPhase,
  RiskLevel,
  TaskPriority,
  TaskStatus,
  AccountType,
  RelationshipStatus,
  OpportunityPriority,
  AgroRole,
  Lead,
  Account,
  Opportunity,
  Matter,
  Task,
  AgroUser,
  CrmStats,
  Deadline,
  DeadlineType,
  DeadlineStatus,
  Activity,
  ActivityEntityType,
  ActivityType,
} from "@shared/agro/types";