import type {
  Account,
  Lead,
  Matter,
  Opportunity,
  Task,
} from "./types.js";

/** Dados 100% fictícios — cenários Agro JGG Group. Nunca usar clientes reais. */

export const SEED_LEADS: Lead[] = [
  {
    id: "LD-001",
    name: "Fazenda Horizonte Ltda.",
    contact: "contato@fazhorizonte-demo.br",
    region: "MT — Sorriso",
    crop: "Soja / milho safrinha",
    source: "Indicação advogado parceiro",
    status: "qualificado",
    owner: "Ana Ribeiro",
    createdAt: "2026-05-28",
    nextContact: "2026-06-10",
    accountId: "AC-101",
    notes:
      "Regularização de 3 glebas e revisão de contratos de arrendamento com vigência até 2028.",
  },
  {
    id: "LD-002",
    name: "Cooperativa Vale Verde (mock)",
    contact: "juridico@valeverde-demo.coop",
    region: "PR — Cascavel",
    crop: "Café / milho",
    source: "Evento cooperativismo",
    status: "qualificando",
    owner: "Carlos Mendes",
    createdAt: "2026-06-02",
    nextContact: "2026-06-12",
    accountId: "AC-102",
    notes: "Governança associativa e padronização de contratos de venda de insumos.",
  },
  {
    id: "LD-003",
    name: "Família Boa Esperança — grupo familiar",
    contact: "familia.boaesperanca@demo.mail",
    region: "GO — Rio Verde",
    crop: "Soja / algodão",
    source: "Indicação cliente",
    status: "novo",
    owner: "Ana Ribeiro",
    createdAt: "2026-06-07",
    nextContact: "2026-06-11",
    accountId: null,
    notes: "Sucessão entre irmãos e reorganização de holdings rurais.",
  },
  {
    id: "LD-004",
    name: "Agro Norte Commodities S.A. (fictícia)",
    contact: "mesa@agronorte-demo.br",
    region: "SP — São Paulo",
    crop: "Trading soja / milho",
    source: "Outbound comercial",
    status: "qualificado",
    owner: "Carlos Mendes",
    createdAt: "2026-05-15",
    nextContact: "2026-06-09",
    accountId: "AC-106",
    notes: "Contratos de compra e venda CIF/FOB e cláusulas de força maior.",
  },
  {
    id: "LD-005",
    name: "Sítio Três Pinheiros",
    contact: "produtor@trespinheiros-demo.br",
    region: "RS — Passo Fundo",
    crop: "Trigo / pecuária de corte",
    source: "Site institucional",
    status: "qualificando",
    owner: "Ana Ribeiro",
    createdAt: "2026-06-04",
    nextContact: "2026-06-13",
    accountId: null,
    notes: "Renegociação de CPR e garantias reais sobre área de 680 ha.",
  },
  {
    id: "LD-006",
    name: "Grupo Irriga Centro-Oeste",
    contact: "diretoria@irriga-demo.br",
    region: "MS — Dourados",
    crop: "Irrigado — cana / soja",
    source: "Referência interna",
    status: "descartado",
    owner: "Carlos Mendes",
    createdAt: "2026-04-20",
    nextContact: null,
    accountId: null,
    notes: "Escopo fora da carteira Agro neste ciclo.",
  },
];

export const SEED_ACCOUNTS: Account[] = [
  {
    id: "AC-101",
    name: "Fazenda Horizonte Ltda.",
    type: "produtor",
    region: "MT — Sorriso",
    areaHa: 4200,
    mainCrop: "Soja",
    owner: "Ana Ribeiro",
    activeMatters: 2,
    activeOpportunities: 1,
    since: "2024-03",
  },
  {
    id: "AC-102",
    name: "Cooperativa Vale Verde",
    type: "cooperativa",
    region: "PR — Cascavel",
    areaHa: 0,
    mainCrop: "Multi",
    owner: "Carlos Mendes",
    activeMatters: 1,
    activeOpportunities: 1,
    since: "2023-11",
  },
  {
    id: "AC-103",
    name: "Família Oliveira Agro",
    type: "familia",
    region: "GO — Rio Verde",
    areaHa: 1850,
    mainCrop: "Soja / algodão",
    owner: "Ana Ribeiro",
    activeMatters: 3,
    activeOpportunities: 0,
    since: "2022-08",
  },
  {
    id: "AC-104",
    name: "CerealTech Indústria (mock)",
    type: "agroindustria",
    region: "MS — Dourados",
    areaHa: 0,
    mainCrop: "Beneficiamento",
    owner: "Carlos Mendes",
    activeMatters: 2,
    activeOpportunities: 1,
    since: "2025-01",
  },
  {
    id: "AC-105",
    name: "Fundo Invest Agro I (fictício)",
    type: "investidor",
    region: "SP — São Paulo",
    areaHa: 0,
    mainCrop: "Portfolio",
    owner: "Ana Ribeiro",
    activeMatters: 1,
    activeOpportunities: 2,
    since: "2025-06",
  },
  {
    id: "AC-106",
    name: "Agro Norte Commodities S.A.",
    type: "trading",
    region: "SP — São Paulo",
    areaHa: 0,
    mainCrop: "Commodities",
    owner: "Carlos Mendes",
    activeMatters: 1,
    activeOpportunities: 1,
    since: "2025-09",
  },
];

export const SEED_OPPORTUNITIES: Opportunity[] = [
  {
    id: "OP-201",
    title: "Regularização fundiária e contratos agrários",
    accountName: "Fazenda Horizonte Ltda.",
    accountId: "AC-101",
    stage: "proposta",
    valueBrl: 185000,
    owner: "Ana Ribeiro",
    expectedClose: "2026-07-15",
    nextContact: "2026-06-10",
    priority: "alta",
    practice: "Imóveis rurais",
  },
  {
    id: "OP-202",
    title: "Governança e contratos associativos",
    accountName: "Cooperativa Vale Verde",
    accountId: "AC-102",
    stage: "qualificacao",
    valueBrl: 92000,
    owner: "Carlos Mendes",
    expectedClose: "2026-08-01",
    nextContact: "2026-06-12",
    priority: "normal",
    practice: "Societário",
  },
  {
    id: "OP-203",
    title: "Due diligence — aquisição de área produtiva",
    accountName: "Fundo Invest Agro I (fictício)",
    accountId: "AC-105",
    stage: "negociacao",
    valueBrl: 240000,
    owner: "Ana Ribeiro",
    expectedClose: "2026-06-30",
    nextContact: "2026-06-09",
    priority: "alta",
    practice: "M&A rural",
  },
  {
    id: "OP-204",
    title: "Renegociação CPR e garantias reais",
    accountName: "Família Oliveira Agro",
    accountId: "AC-103",
    stage: "contrato",
    valueBrl: 68000,
    owner: "Ana Ribeiro",
    expectedClose: "2026-06-12",
    nextContact: null,
    priority: "alta",
    practice: "Crédito rural",
  },
  {
    id: "OP-205",
    title: "Compliance ambiental — unidade industrial",
    accountName: "CerealTech Indústria (mock)",
    accountId: "AC-104",
    stage: "proposta",
    valueBrl: 110000,
    owner: "Carlos Mendes",
    expectedClose: "2026-07-22",
    nextContact: "2026-06-14",
    priority: "normal",
    practice: "Ambiental",
  },
  {
    id: "OP-206",
    title: "Contratos de barter e hedge — safra 2026/27",
    accountName: "Agro Norte Commodities S.A.",
    accountId: "AC-106",
    stage: "negociacao",
    valueBrl: 156000,
    owner: "Carlos Mendes",
    expectedClose: "2026-07-08",
    nextContact: "2026-06-10",
    priority: "alta",
    practice: "Contratos agrários",
  },
];

export const SEED_MATTERS: Matter[] = [
  {
    id: "MT-301",
    title: "CAR e georreferenciamento — gleba norte",
    accountName: "Fazenda Horizonte Ltda.",
    accountId: "AC-101",
    practice: "Regularização fundiária",
    status: "em_andamento",
    risk: "medio",
    deadline: "2026-06-18",
    owner: "Ana Ribeiro",
    description: "Retificação de área e consolidação documental para registro.",
  },
  {
    id: "MT-302",
    title: "Defesa administrativa — embargo APP",
    accountName: "Família Oliveira Agro",
    accountId: "AC-103",
    practice: "Contencioso rural",
    status: "aberta",
    risk: "alto",
    deadline: "2026-06-10",
    owner: "Carlos Mendes",
    description: "Manifestação em auto de infração ambiental — prazo fatal.",
  },
  {
    id: "MT-303",
    title: "Revisão contratos de arrendamento rural",
    accountName: "Cooperativa Vale Verde",
    accountId: "AC-102",
    practice: "Contratos agrários",
    status: "aguardando",
    risk: "baixo",
    deadline: "2026-06-25",
    owner: "Carlos Mendes",
    description: "Aguardando minuta da contraparte para parecer final.",
  },
  {
    id: "MT-304",
    title: "Holding familiar e sucessão patrimonial",
    accountName: "Família Oliveira Agro",
    accountId: "AC-103",
    practice: "Planejamento sucessório",
    status: "em_andamento",
    risk: "medio",
    deadline: "2026-07-05",
    owner: "Ana Ribeiro",
    description: "Estruturação societária e acordo de quotistas entre gerações.",
  },
  {
    id: "MT-305",
    title: "Licenciamento operacional — silo armazenagem",
    accountName: "CerealTech Indústria (mock)",
    accountId: "AC-104",
    practice: "Ambiental / compliance",
    status: "em_andamento",
    risk: "critico",
    deadline: "2026-06-09",
    owner: "Carlos Mendes",
    description: "Condicionante ambiental com vencimento em 48h.",
  },
  {
    id: "MT-306",
    title: "Parecer tributário — incentivos ao agro",
    accountName: "Agro Norte Commodities S.A.",
    accountId: "AC-106",
    practice: "Tributário aplicado ao agro",
    status: "em_andamento",
    risk: "medio",
    deadline: "2026-06-20",
    owner: "Ana Ribeiro",
    description: "Análise de benefícios fiscais em operações de exportação.",
  },
  {
    id: "MT-307",
    title: "Ação reivindicatória — conflito de posse",
    accountName: "Fazenda Horizonte Ltda.",
    accountId: "AC-101",
    practice: "Contencioso rural",
    status: "aberta",
    risk: "alto",
    deadline: "2026-06-16",
    owner: "Carlos Mendes",
    description: "Disputa de limites com vizinho — audiência de conciliação.",
  },
];

export const SEED_TASKS: Task[] = [
  {
    id: "TK-401",
    title: "Enviar proposta revisada — regularização Horizonte",
    relatedTo: "OP-201",
    type: "comercial",
    priority: "alta",
    status: "pendente",
    dueDate: "2026-06-09",
    owner: "Ana Ribeiro",
  },
  {
    id: "TK-402",
    title: "Protocolar defesa administrativa — embargo APP",
    relatedTo: "MT-302",
    type: "juridica",
    priority: "urgente",
    status: "atrasada",
    dueDate: "2026-06-08",
    owner: "Carlos Mendes",
  },
  {
    id: "TK-403",
    title: "Reunião diagnóstico — Família Boa Esperança",
    relatedTo: "LD-003",
    type: "comercial",
    priority: "media",
    status: "pendente",
    dueDate: "2026-06-11",
    owner: "Ana Ribeiro",
  },
  {
    id: "TK-404",
    title: "Coletar matrículas e CAR — gleba norte",
    relatedTo: "MT-301",
    type: "operacional",
    priority: "alta",
    status: "em_andamento",
    dueDate: "2026-06-12",
    owner: "Ana Ribeiro",
  },
  {
    id: "TK-405",
    title: "Minuta contrato arrendamento — Vale Verde",
    relatedTo: "MT-303",
    type: "juridica",
    priority: "media",
    status: "pendente",
    dueDate: "2026-06-20",
    owner: "Carlos Mendes",
  },
  {
    id: "TK-406",
    title: "Follow-up due diligence — Fundo Invest",
    relatedTo: "OP-203",
    type: "comercial",
    priority: "alta",
    status: "em_andamento",
    dueDate: "2026-06-10",
    owner: "Ana Ribeiro",
  },
  {
    id: "TK-407",
    title: "Atender condicionante licenciamento — CerealTech",
    relatedTo: "MT-305",
    type: "juridica",
    priority: "urgente",
    status: "pendente",
    dueDate: "2026-06-09",
    owner: "Carlos Mendes",
  },
  {
    id: "TK-408",
    title: "Alinhar cláusulas barter — Agro Norte",
    relatedTo: "OP-206",
    type: "comercial",
    priority: "alta",
    status: "pendente",
    dueDate: "2026-06-10",
    owner: "Carlos Mendes",
  },
];

export const OPPORTUNITY_STAGES = [
  { id: "qualificacao" as const, label: "Qualificação" },
  { id: "proposta" as const, label: "Proposta" },
  { id: "negociacao" as const, label: "Negociação" },
  { id: "contrato" as const, label: "Contrato" },
  { id: "perdido" as const, label: "Perdido" },
];