// Dataset de demonstração usado APENAS por testes. Mantém cenários
// coerentes (pipeline, prazos, riscos) sem poluir o seed de produção,
// que agora inicia vazio. Não importar em código de runtime.
import type {
  Account,
  Activity,
  Deadline,
  Lead,
  Matter,
  Opportunity,
  Task,
} from "./types.js";

export const FIXTURE_LEADS: Lead[] = [
  {
    id: "LD-001",
    name: "Fazenda Horizonte Ltda.",
    contact: "contato@fazhorizonte-demo.br",
    region: "MT — Sorriso",
    crop: "Soja / milho safrinha",
    source: "Indicação advogado parceiro",
    status: "qualificado",
    owner: "Ana Ribeiro",
    createdAt: "2026-05-28",
    nextContact: "2026-06-10",
    accountId: "AC-101",
    leadType: "Produtor rural",
    legalPain: "Regularização fundiária e contratos de arrendamento",
    interestArea: "Regularização de imóveis rurais",
    priority: "alta",
    convertedOpportunityId: "OP-201",
    notes:
      "Regularização de 3 glebas e revisão de contratos de arrendamento com vigência até 2028.",
  },
  {
    id: "LD-002",
    name: "Cooperativa Vale Verde (mock)",
    contact: "juridico@valeverde-demo.coop",
    region: "PR — Cascavel",
    crop: "Café / milho",
    source: "Evento cooperativismo",
    status: "qualificando",
    owner: "Carlos Mendes",
    createdAt: "2026-06-02",
    nextContact: "2026-06-12",
    accountId: "AC-102",
    leadType: "Cooperativa",
    legalPain: "Governança associativa e padronização contratual",
    interestArea: "Operações societárias e reorganizações",
    priority: "media",
    notes: "Governança associativa e padronização de contratos de venda de insumos.",
  },
  {
    id: "LD-003",
    name: "Família Boa Esperança — grupo familiar",
    contact: "familia.boaesperanca@demo.mail",
    region: "GO — Rio Verde",
    crop: "Soja / algodão",
    source: "Indicação cliente",
    status: "novo",
    owner: "Ana Ribeiro",
    createdAt: "2026-06-07",
    nextContact: "2026-06-11",
    accountId: null,
    leadType: "Família empresária",
    legalPain: "Sucessão entre irmãos e reorganização de holdings",
    interestArea: "Planejamento patrimonial e sucessório",
    priority: "alta",
    notes: "Sucessão entre irmãos e reorganização de holdings rurais.",
  },
  {
    id: "LD-004",
    name: "Agro Norte Commodities S.A. (fictícia)",
    contact: "mesa@agronorte-demo.br",
    region: "SP — São Paulo",
    crop: "Trading soja / milho",
    source: "Outbound comercial",
    status: "qualificado",
    owner: "Carlos Mendes",
    createdAt: "2026-05-15",
    nextContact: "2026-06-09",
    accountId: "AC-106",
    leadType: "Trading",
    legalPain: "Contratos CIF/FOB e cláusulas de força maior",
    interestArea: "Contratos agrários e comerciais",
    priority: "alta",
    notes: "Contratos de compra e venda CIF/FOB e cláusulas de força maior.",
  },
  {
    id: "LD-005",
    name: "Sítio Três Pinheiros",
    contact: "produtor@trespinheiros-demo.br",
    region: "RS — Passo Fundo",
    crop: "Trigo / pecuária de corte",
    source: "Site institucional",
    status: "qualificando",
    owner: "Ana Ribeiro",
    createdAt: "2026-06-04",
    nextContact: "2026-06-13",
    accountId: null,
    leadType: "Produtor rural",
    legalPain: "Renegociação de CPR e garantias reais",
    interestArea: "Crédito rural, garantias e renegociação",
    priority: "media",
    notes: "Renegociação de CPR e garantias reais sobre área de 680 ha.",
  },
  {
    id: "LD-007",
    name: "Holding Pantanal Agro S.A. (fictícia)",
    contact: "mesa@pantanalagro-demo.br",
    region: "MT — Rondonópolis",
    crop: "Pecuária / soja irrigada",
    source: "M&A advisory",
    status: "qualificado",
    owner: "Carlos Mendes",
    createdAt: "2026-05-20",
    nextContact: "2026-06-14",
    accountId: "AC-107",
    leadType: "Investidor",
    legalPain: "Reorganização societária pós-aquisição",
    interestArea: "Operações societárias e reorganizações",
    priority: "alta",
    notes:
      "Reorganização societária pós-aquisição de fazendas em MT e MS.",
  },
  {
    id: "LD-006",
    name: "Grupo Irriga Centro-Oeste",
    contact: "diretoria@irriga-demo.br",
    region: "MS — Dourados",
    crop: "Irrigado — cana / soja",
    source: "Referência interna",
    status: "descartado",
    owner: "Carlos Mendes",
    createdAt: "2026-04-20",
    nextContact: null,
    accountId: null,
    leadType: "Produtor rural",
    legalPain: "Escopo fora da carteira Agro",
    interestArea: "Ambiental, licenciamento e compliance rural",
    priority: "baixa",
    notes: "Escopo fora da carteira Agro neste ciclo.",
  },
];

export const FIXTURE_ACCOUNTS: Account[] = [
  {
    id: "AC-101",
    name: "Fazenda Horizonte Ltda.",
    type: "produtor",
    region: "MT — Sorriso",
    areaHa: 4200,
    mainCrop: "Soja",
    owner: "Ana Ribeiro",
    activeMatters: 2,
    activeOpportunities: 1,
    since: "2024-03",
    properties: ["Gleba Norte (1.800 ha)", "Gleba Sul (2.400 ha)"],
    contacts: ["contato@fazhorizonte-demo.br", "juridico@fazhorizonte-demo.br"],
    contractedAreas: ["Regularização fundiária", "Contratos agrários"],
    mappedRisks: ["Pendência CAR gleba norte", "Conflito de posse vizinho"],
    relationshipStatus: "ativo",
  },
  {
    id: "AC-102",
    name: "Cooperativa Vale Verde",
    type: "cooperativa",
    region: "PR — Cascavel",
    areaHa: 0,
    mainCrop: "Multi",
    owner: "Carlos Mendes",
    activeMatters: 1,
    activeOpportunities: 1,
    since: "2023-11",
    properties: ["Sede administrativa", "Unidade armazenagem"],
    contacts: ["juridico@valeverde-demo.coop"],
    contractedAreas: ["Governança associativa"],
    mappedRisks: ["Padronização contratual pendente"],
    relationshipStatus: "em_expansao",
  },
  {
    id: "AC-103",
    name: "Família Oliveira Agro",
    type: "familia",
    region: "GO — Rio Verde",
    areaHa: 1850,
    mainCrop: "Soja / algodão",
    owner: "Ana Ribeiro",
    activeMatters: 3,
    activeOpportunities: 0,
    since: "2022-08",
    properties: ["Fazenda Oliveira I", "Fazenda Oliveira II"],
    contacts: ["familia.oliveira@demo.mail"],
    contractedAreas: ["Contencioso ambiental", "Sucessão patrimonial"],
    mappedRisks: ["Embargo APP", "Conflito sucessório"],
    relationshipStatus: "em_risco",
  },
  {
    id: "AC-104",
    name: "CerealTech Indústria (mock)",
    type: "agroindustria",
    region: "MS — Dourados",
    areaHa: 0,
    mainCrop: "Beneficiamento",
    owner: "Carlos Mendes",
    activeMatters: 2,
    activeOpportunities: 1,
    since: "2025-01",
    properties: ["Unidade industrial Dourados", "Silo armazenagem"],
    contacts: ["compliance@cerealtech-demo.br"],
    contractedAreas: ["Compliance ambiental"],
    mappedRisks: ["Condicionante licenciamento vencendo"],
    relationshipStatus: "ativo",
  },
  {
    id: "AC-105",
    name: "Fundo Invest Agro I (fictício)",
    type: "investidor",
    region: "SP — São Paulo",
    areaHa: 0,
    mainCrop: "Portfolio",
    owner: "Ana Ribeiro",
    activeMatters: 1,
    activeOpportunities: 2,
    since: "2025-06",
    properties: ["Portfolio MT/GO"],
    contacts: ["mesa@fundoinvest-demo.br"],
    contractedAreas: ["Due diligence M&A"],
    mappedRisks: ["Exposição regulatória em novas aquisições"],
    relationshipStatus: "em_expansao",
  },
  {
    id: "AC-106",
    name: "Agro Norte Commodities S.A.",
    type: "trading",
    region: "SP — São Paulo",
    areaHa: 0,
    mainCrop: "Commodities",
    owner: "Carlos Mendes",
    activeMatters: 1,
    activeOpportunities: 1,
    since: "2025-09",
    properties: ["Mesa SP", "Escritório Santos"],
    contacts: ["mesa@agronorte-demo.br"],
    contractedAreas: ["Contratos comerciais", "Tributário aplicado"],
    mappedRisks: ["Cláusulas barter em revisão"],
    relationshipStatus: "ativo",
  },
  {
    id: "AC-107",
    name: "Holding Pantanal Agro S.A.",
    type: "investidor",
    region: "MT — Rondonópolis",
    areaHa: 0,
    mainCrop: "Portfolio",
    owner: "Carlos Mendes",
    activeMatters: 1,
    activeOpportunities: 1,
    since: "2026-02",
    properties: ["SPE Pantanal Norte", "SPE Pantanal Sul"],
    contacts: ["mesa@pantanalagro-demo.br"],
    contractedAreas: ["Reorganização societária"],
    mappedRisks: ["Integração pós-M&A"],
    relationshipStatus: "em_expansao",
  },
];

export const FIXTURE_OPPORTUNITIES: Opportunity[] = [
  {
    id: "OP-201",
    title: "Regularização fundiária e contratos agrários",
    accountName: "Fazenda Horizonte Ltda.",
    accountId: "AC-101",
    stage: "proposta_enviada",
    valueBrl: 185000,
    owner: "Ana Ribeiro",
    expectedClose: "2026-07-15",
    nextContact: "2026-06-10",
    priority: "alta",
    practice: "Regularização de imóveis rurais",
    probability: 65,
    nextStep: "Aguardar retorno sobre proposta revisada",
    leadId: "LD-001",
  },
  {
    id: "OP-202",
    title: "Governança e contratos associativos",
    accountName: "Cooperativa Vale Verde",
    accountId: "AC-102",
    stage: "diagnostico_realizado",
    valueBrl: 92000,
    owner: "Carlos Mendes",
    expectedClose: "2026-08-01",
    nextContact: "2026-06-12",
    priority: "normal",
    practice: "Operações societárias e reorganizações",
    probability: 40,
    nextStep: "Elaborar proposta de governança",
  },
  {
    id: "OP-203",
    title: "Due diligence — aquisição de área produtiva",
    accountName: "Fundo Invest Agro I (fictício)",
    accountId: "AC-105",
    stage: "negociacao",
    valueBrl: 240000,
    owner: "Ana Ribeiro",
    expectedClose: "2026-06-30",
    nextContact: "2026-06-09",
    priority: "alta",
    practice: "Operações societárias e reorganizações",
    probability: 75,
    nextStep: "Fechar escopo e condições comerciais",
  },
  {
    id: "OP-204",
    title: "Renegociação CPR e garantias reais",
    accountName: "Família Oliveira Agro",
    accountId: "AC-103",
    stage: "contrato",
    valueBrl: 68000,
    owner: "Ana Ribeiro",
    expectedClose: "2026-06-12",
    nextContact: null,
    priority: "alta",
    practice: "Crédito rural, garantias e renegociação",
    probability: 100,
    nextStep: "Formalizar contrato assinado",
  },
  {
    id: "OP-205",
    title: "Compliance ambiental — unidade industrial",
    accountName: "CerealTech Indústria (mock)",
    accountId: "AC-104",
    stage: "proposta_elaboracao",
    valueBrl: 110000,
    owner: "Carlos Mendes",
    expectedClose: "2026-07-22",
    nextContact: "2026-06-14",
    priority: "normal",
    practice: "Ambiental, licenciamento e compliance rural",
    probability: 50,
    nextStep: "Finalizar minuta de proposta",
  },
  {
    id: "OP-206",
    title: "Contratos de barter e hedge — safra 2026/27",
    accountName: "Agro Norte Commodities S.A.",
    accountId: "AC-106",
    stage: "negociacao",
    valueBrl: 156000,
    owner: "Carlos Mendes",
    expectedClose: "2026-07-08",
    nextContact: "2026-06-10",
    priority: "alta",
    practice: "Contratos agrários e comerciais",
    probability: 70,
    nextStep: "Alinhar cláusulas de barter",
  },
  {
    id: "OP-207",
    title: "Reorganização societária — incorporação de fazendas",
    accountName: "Holding Pantanal Agro S.A.",
    accountId: "AC-107",
    stage: "novo_contato",
    valueBrl: 198000,
    owner: "Carlos Mendes",
    expectedClose: "2026-08-15",
    nextContact: "2026-06-14",
    priority: "alta",
    practice: "Operações societárias e reorganizações",
    probability: 45,
    nextStep: "Mapear SPEs e estrutura atual",
  },
  {
    id: "OP-208",
    title: "Planejamento sucessório — grupo familiar GO",
    accountName: "Família Oliveira Agro",
    accountId: "AC-103",
    stage: "proposta_elaboracao",
    valueBrl: 125000,
    owner: "Ana Ribeiro",
    expectedClose: "2026-07-30",
    nextContact: "2026-06-11",
    priority: "normal",
    practice: "Planejamento patrimonial e sucessório",
    probability: 55,
    nextStep: "Consolidar proposta sucessória",
  },
  {
    id: "OP-209",
    title: "Assessoria tributária — safra anterior (arquivada)",
    accountName: "Grupo Irriga Centro-Oeste",
    stage: "arquivado",
    valueBrl: 45000,
    owner: "Carlos Mendes",
    expectedClose: "2026-04-01",
    nextContact: null,
    priority: "normal",
    practice: "Tributário aplicado ao agro",
    probability: 0,
    nextStep: "Sem ação — arquivo comercial",
  },
];

export const FIXTURE_MATTERS: Matter[] = [
  {
    id: "MT-301",
    title: "CAR e georreferenciamento — gleba norte",
    accountName: "Fazenda Horizonte Ltda.",
    accountId: "AC-101",
    practice: "Regularização de imóveis rurais",
    status: "em_andamento",
    risk: "medio",
    deadline: "2026-06-18",
    owner: "Ana Ribeiro",
    description: "Retificação de área e consolidação documental para registro.",
    urgency: "normal",
    pendingDocuments: ["Matrícula atualizada", "Memorial descritivo"],
    nextSteps: "Coletar matrículas e protocolar retificação",
    phase: "extrajudicial",
    court: "CRI de Sorriso/MT",
    opportunityId: "OP-201",
  },
  {
    id: "MT-302",
    title: "Defesa administrativa — embargo APP",
    accountName: "Família Oliveira Agro",
    accountId: "AC-103",
    practice: "Contencioso estratégico e disputas rurais",
    status: "aberta",
    risk: "alto",
    deadline: "2026-06-10",
    owner: "Carlos Mendes",
    description: "Manifestação em auto de infração ambiental — prazo fatal.",
    urgency: "critica",
    pendingDocuments: ["Laudo técnico", "Procuração"],
    nextSteps: "Protocolar defesa administrativa",
    phase: "extrajudicial",
    court: "SEMA/MT — processo administrativo",
    opposingParty: "Estado de Mato Grosso (SEMA)",
    claimValueBrl: 420000,
  },
  {
    id: "MT-303",
    title: "Revisão contratos de arrendamento rural",
    accountName: "Cooperativa Vale Verde",
    accountId: "AC-102",
    practice: "Contratos agrários e comerciais",
    status: "aguardando",
    risk: "baixo",
    deadline: "2026-06-25",
    owner: "Carlos Mendes",
    description: "Aguardando minuta da contraparte para parecer final.",
    urgency: "normal",
    pendingDocuments: ["Minuta contraparte"],
    nextSteps: "Aguardar retorno da cooperativa",
  },
  {
    id: "MT-304",
    title: "Holding familiar e sucessão patrimonial",
    accountName: "Família Oliveira Agro",
    accountId: "AC-103",
    practice: "Planejamento patrimonial e sucessório",
    status: "em_andamento",
    risk: "medio",
    deadline: "2026-07-05",
    owner: "Ana Ribeiro",
    description: "Estruturação societária e acordo de quotistas entre gerações.",
    urgency: "alta",
    pendingDocuments: ["Acordo de quotistas", "Balanços patrimoniais"],
    nextSteps: "Reunião com família — alinhamento sucessório",
  },
  {
    id: "MT-305",
    title: "Licenciamento operacional — silo armazenagem",
    accountName: "CerealTech Indústria (mock)",
    accountId: "AC-104",
    practice: "Ambiental, licenciamento e compliance rural",
    status: "em_andamento",
    risk: "critico",
    deadline: "2026-06-09",
    owner: "Carlos Mendes",
    description: "Condicionante ambiental com vencimento em 48h.",
    urgency: "critica",
    pendingDocuments: ["Relatório de atendimento", "ART responsável técnico"],
    nextSteps: "Protocolar atendimento à condicionante",
  },
  {
    id: "MT-306",
    title: "Parecer tributário — incentivos ao agro",
    accountName: "Agro Norte Commodities S.A.",
    accountId: "AC-106",
    practice: "Tributário aplicado ao agro",
    status: "em_andamento",
    risk: "medio",
    deadline: "2026-06-20",
    owner: "Ana Ribeiro",
    description: "Análise de benefícios fiscais em operações de exportação.",
    urgency: "normal",
    pendingDocuments: ["DFEs exportação", "Contratos de hedge"],
    nextSteps: "Emitir parecer preliminar",
  },
  {
    id: "MT-307",
    title: "Ação reivindicatória — conflito de posse",
    accountName: "Fazenda Horizonte Ltda.",
    accountId: "AC-101",
    practice: "Contencioso estratégico e disputas rurais",
    status: "aberta",
    risk: "alto",
    deadline: "2026-06-16",
    owner: "Carlos Mendes",
    description: "Disputa de limites com vizinho — audiência de conciliação.",
    urgency: "alta",
    pendingDocuments: ["Plantas georreferenciadas", "Testemunhas"],
    nextSteps: "Preparar petição e provas para audiência",
    cnjNumber: "0001234-56.2026.8.11.0040",
    court: "2ª Vara Cível de Sorriso/MT",
    phase: "conhecimento",
    opposingParty: "Agropecuária Divisa Norte Ltda. (fictícia)",
    claimValueBrl: 1850000,
  },
  {
    id: "MT-308",
    title: "Incorporação de SPEs rurais — Pantanal Agro",
    accountName: "Holding Pantanal Agro S.A.",
    accountId: "AC-107",
    practice: "Operações societárias e reorganizações",
    status: "em_andamento",
    risk: "medio",
    deadline: "2026-06-22",
    owner: "Carlos Mendes",
    description: "Consolidação de ativos e revisão de acordo de quotistas.",
    urgency: "normal",
    pendingDocuments: ["Minuta incorporação", "Laudos de avaliação"],
    nextSteps: "Revisar minuta com cliente",
  },
  {
    id: "MT-309",
    title: "Parecer crédito rural — garantias fiduciárias",
    accountName: "Sítio Três Pinheiros",
    practice: "Crédito rural, garantias e renegociação",
    status: "aberta",
    risk: "alto",
    deadline: "2026-06-11",
    owner: "Ana Ribeiro",
    description: "Análise de penhor rural e renegociação com agente financeiro.",
    urgency: "alta",
    pendingDocuments: ["CPR vigente", "Matrícula da área"],
    nextSteps: "Emitir parecer sobre garantias",
    phase: "consultivo",
    opportunityId: "OP-204",
  },
];

/** Prazos processuais — múltiplos por demanda, com tipo fatal/ordinatório. */
export const FIXTURE_DEADLINES: Deadline[] = [
  {
    id: "DL-501",
    matterId: "MT-302",
    title: "Protocolo da defesa administrativa — auto de infração",
    type: "fatal",
    status: "pendente",
    dueDate: "2026-06-10",
    owner: "Carlos Mendes",
    completedAt: null,
    notes: "Prazo de 20 dias do AI. Improrrogável.",
  },
  {
    id: "DL-502",
    matterId: "MT-302",
    title: "Juntada de laudo técnico complementar",
    type: "ordinatorio",
    status: "pendente",
    dueDate: "2026-06-17",
    owner: "Carlos Mendes",
    completedAt: null,
  },
  {
    id: "DL-503",
    matterId: "MT-307",
    title: "Audiência de conciliação (art. 334 CPC)",
    type: "fatal",
    status: "pendente",
    dueDate: "2026-06-16",
    owner: "Carlos Mendes",
    completedAt: null,
    notes: "Comparecimento obrigatório — multa por ausência injustificada.",
  },
  {
    id: "DL-504",
    matterId: "MT-307",
    title: "Contestação (15 dias úteis da audiência)",
    type: "fatal",
    status: "pendente",
    dueDate: "2026-07-07",
    owner: "Carlos Mendes",
    completedAt: null,
  },
  {
    id: "DL-505",
    matterId: "MT-307",
    title: "Rol de testemunhas",
    type: "ordinatorio",
    status: "pendente",
    dueDate: "2026-06-13",
    owner: "Carlos Mendes",
    completedAt: null,
  },
  {
    id: "DL-506",
    matterId: "MT-305",
    title: "Atendimento à condicionante ambiental",
    type: "fatal",
    status: "cumprido",
    dueDate: "2026-06-09",
    owner: "Carlos Mendes",
    completedAt: "2026-06-08",
    notes: "Protocolado com relatório e ART.",
  },
  {
    id: "DL-507",
    matterId: "MT-301",
    title: "Protocolo da retificação de área no CRI",
    type: "ordinatorio",
    status: "pendente",
    dueDate: "2026-06-18",
    owner: "Ana Ribeiro",
    completedAt: null,
  },
  {
    id: "DL-508",
    matterId: "MT-309",
    title: "Entrega do parecer sobre garantias ao cliente",
    type: "ordinatorio",
    status: "pendente",
    dueDate: "2026-06-11",
    owner: "Ana Ribeiro",
    completedAt: null,
  },
];

/** Interações registradas — timeline comercial e jurídica. */
export const FIXTURE_ACTIVITIES: Activity[] = [
  {
    id: "ACT-601",
    entityType: "lead",
    entityId: "LD-001",
    type: "reuniao",
    summary:
      "Diagnóstico inicial em Sorriso: 3 glebas sem georreferenciamento, 2 contratos de arrendamento vencendo em 2028.",
    date: "2026-05-29",
    owner: "Ana Ribeiro",
    createdAt: "2026-05-29T14:30:00Z",
  },
  {
    id: "ACT-602",
    entityType: "lead",
    entityId: "LD-001",
    type: "sistema",
    summary: "Lead convertido em oportunidade OP-201.",
    date: "2026-06-01",
    owner: "Ana Ribeiro",
    createdAt: "2026-06-01T09:00:00Z",
  },
  {
    id: "ACT-603",
    entityType: "opportunity",
    entityId: "OP-201",
    type: "email",
    summary: "Proposta revisada enviada ao gestor da fazenda — escopo fundiário + contratos.",
    date: "2026-06-05",
    owner: "Ana Ribeiro",
    createdAt: "2026-06-05T11:20:00Z",
  },
  {
    id: "ACT-604",
    entityType: "lead",
    entityId: "LD-002",
    type: "ligacao",
    summary: "Conselho da cooperativa avalia proposta de diagnóstico de governança.",
    date: "2026-06-08",
    owner: "Carlos Mendes",
    createdAt: "2026-06-08T16:45:00Z",
  },
  {
    id: "ACT-605",
    entityType: "matter",
    entityId: "MT-307",
    type: "reuniao",
    summary: "Alinhamento com cliente sobre estratégia para audiência de conciliação.",
    date: "2026-06-09",
    owner: "Carlos Mendes",
    createdAt: "2026-06-09T10:00:00Z",
  },
  {
    id: "ACT-606",
    entityType: "account",
    entityId: "AC-101",
    type: "visita",
    summary: "Visita à sede da fazenda — apresentação da equipe jurídica e mapeamento de riscos.",
    date: "2026-06-03",
    owner: "Ana Ribeiro",
    createdAt: "2026-06-03T15:00:00Z",
  },
  {
    id: "ACT-607",
    entityType: "opportunity",
    entityId: "OP-206",
    type: "whatsapp",
    summary: "Diretoria sinalizou aceite das cláusulas de barter; pendente validação do hedge.",
    date: "2026-06-10",
    owner: "Carlos Mendes",
    createdAt: "2026-06-10T18:10:00Z",
  },
  {
    id: "ACT-608",
    entityType: "matter",
    entityId: "MT-302",
    type: "nota",
    summary: "Laudo técnico recebido do engenheiro ambiental — revisar antes do protocolo.",
    date: "2026-06-09",
    owner: "Carlos Mendes",
    createdAt: "2026-06-09T17:30:00Z",
  },
];

export const FIXTURE_TASKS: Task[] = [
  {
    id: "TK-401",
    title: "Enviar proposta revisada — regularização Horizonte",
    relatedTo: "OP-201",
    type: "comercial",
    priority: "alta",
    status: "pendente",
    dueDate: "2026-06-09",
    owner: "Ana Ribeiro",
  },
  {
    id: "TK-402",
    title: "Protocolar defesa administrativa — embargo APP",
    relatedTo: "MT-302",
    type: "juridica",
    priority: "urgente",
    status: "atrasada",
    dueDate: "2026-06-08",
    owner: "Carlos Mendes",
  },
  {
    id: "TK-403",
    title: "Reunião diagnóstico — Família Boa Esperança",
    relatedTo: "LD-003",
    type: "comercial",
    priority: "media",
    status: "pendente",
    dueDate: "2026-06-11",
    owner: "Ana Ribeiro",
  },
  {
    id: "TK-404",
    title: "Coletar matrículas e CAR — gleba norte",
    relatedTo: "MT-301",
    type: "operacional",
    priority: "alta",
    status: "em_andamento",
    dueDate: "2026-06-12",
    owner: "Ana Ribeiro",
  },
  {
    id: "TK-405",
    title: "Minuta contrato arrendamento — Vale Verde",
    relatedTo: "MT-303",
    type: "juridica",
    priority: "media",
    status: "pendente",
    dueDate: "2026-06-20",
    owner: "Carlos Mendes",
  },
  {
    id: "TK-406",
    title: "Follow-up due diligence — Fundo Invest",
    relatedTo: "OP-203",
    type: "comercial",
    priority: "alta",
    status: "em_andamento",
    dueDate: "2026-06-10",
    owner: "Ana Ribeiro",
  },
  {
    id: "TK-407",
    title: "Atender condicionante licenciamento — CerealTech",
    relatedTo: "MT-305",
    type: "juridica",
    priority: "urgente",
    status: "pendente",
    dueDate: "2026-06-09",
    owner: "Carlos Mendes",
  },
  {
    id: "TK-408",
    title: "Alinhar cláusulas barter — Agro Norte",
    relatedTo: "OP-206",
    type: "comercial",
    priority: "alta",
    status: "pendente",
    dueDate: "2026-06-10",
    owner: "Carlos Mendes",
  },
  {
    id: "TK-409",
    title: "Minuta incorporação — Holding Pantanal",
    relatedTo: "MT-308",
    type: "juridica",
    priority: "alta",
    status: "pendente",
    dueDate: "2026-06-15",
    owner: "Carlos Mendes",
  },
  {
    id: "TK-410",
    title: "Proposta sucessória — Família Oliveira",
    relatedTo: "OP-208",
    type: "comercial",
    priority: "media",
    status: "em_andamento",
    dueDate: "2026-06-11",
    owner: "Ana Ribeiro",
  },
];

export const FIXTURES = {
  leads: FIXTURE_LEADS,
  accounts: FIXTURE_ACCOUNTS,
  opportunities: FIXTURE_OPPORTUNITIES,
  matters: FIXTURE_MATTERS,
  tasks: FIXTURE_TASKS,
  deadlines: FIXTURE_DEADLINES,
  activities: FIXTURE_ACTIVITIES,
};
